version: 1.0.{build}
branches:
  only:
  - master
  - develop
environment:
  MYGET_API_KEY:
    secure: 87c7971f-6933-459f-bfb7-8b52044ed1b6
install:
- ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off