version: 1.0.{build}
branches:
  only:
  - master
  - develop
environment:
  MYGET_API_KEY:
    secure: PNr+oTt872ohvMfGGwxBqVawa7BnFMgwHD7yN/FSsgx1IP0WQlmiZ91+KmrYu+NV
install:
- ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off